export const CREATE_REPORT_ERROR = 'CREATE_REPORT_ERROR';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';

export const DELETE_REPORT_ERROR = 'DELETE_REPORT_ERROR';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';

export const UNDELETE_REPORT_ERROR = 'UNDELETE_REPORT_ERROR';

export const UPDATE_REPORT_ERROR = 'UPDATE_REPORT_ERROR';
export const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';

export const FILTER_REPORTS = 'FILTER_REPORTS';
export const LOAD_REPORTS_SUCCESS = 'LOAD_REPORTS_SUCCESS';
export const UNLOAD_REPORTS_SUCCESS = 'UNLOAD_REPORTS_SUCCESS';
export const LOAD_REPORT_FOR_EDITING = 'LOAD_REPORT_FOR_EDITING';
