export const LOAD_CMMDATA_EMPLOYEES_SUCCESS = 'LOAD_CMMDATA_EMPLOYEES_SUCCESS';
export const UNLOAD_CMMDATA_EMPLOYEES_SUCCESS = 'UNLOAD_CMMDATA_EMPLOYEES_SUCCESS';
export const FILTER_EMPLOYEES = 'FILTER_EMPLOYEES';

